default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>

development:
  <<: *default
  database: sroc-tcm-admin_development

test:
  <<: *default
  database: sroc-tcm-admin_test

production:
  <<: *default
  database: sroc-tcm-admin_production
