default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  host: <%= ENV["POSTGRES_HOST"] || "localhost" %>
  port: <%= ENV["POSTGRES_PORT"] || 5432 %>
  username: <%= ENV["POSTGRES_USER"] || "vagrant" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "vagrant" %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "sroc-tcm-admin" %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_DB_TEST"] || "sroc-tcm-admin_test" %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "sroc" %>
