name: CI

on:
  push:

jobs:
  build:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest
    env:
      DEVISE_MAILER_SENDER: no-reply@example.com
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: pinafore
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      REDIS_URL: "redis://localhost:6379"
      FILE_UPLOAD_ACCESS_KEY: iamanawss3accesskey
      FILE_UPLOAD_SECRET_KEY: iamanawss3secretkey
      FILE_UPLOAD_BUCKET: file-uploads-example-gov-uk
      ARCHIVE_BUCKET: file-archive-example-gov-uk

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12.5-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pinafore
          POSTGRES_DB: sroc-tcm-admin_test
        # Maps tcp port 5432 on service container to the host
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started. You must have this so the runner knows to wait till
        # postgres is up and running before proceeding
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of sonarcloud analysis

      # Before we do anything, check we haven't accidentally left any `:focus` or `focus: :true` statements in the
      # tests
      #
      # Reworking of https://stackoverflow.com/a/21788642/6117745
      - name: Temporary tag check
        run: |
          ! grep --exclude=spec_helper.rb -R ':focus\|focus:' spec

      # We don't have to specify the ruby version, or grab it from .ruby-verion. This action supports reading the
      # version from .ruby-verion itself
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      # Coverband, the gem we use to track production code usage depends on being able to connect to redis
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6

      - name: Database migrations
        run: |
          RAILS_ENV=test bundle exec rake db:migrate

      # Run linting first. No point running the tests if there is a linting issue
      - name: Run lint check
        run: |
          bundle exec rubocop --format progress --format json --out rubocop-result.json

      # This includes an extra run step. The sonarcloud analysis will be run in a docker container with the current
      # folder mounted as `/github/workspace`. The problem is when the .resultset.json file is generated it will
      # reference the code in the current folder. So to enable sonarcloud to matchup code coverage with the files we use
      # sed to update the references in .resultset.json
      # https://community.sonarsource.com/t/code-coverage-doesnt-work-with-github-action/16747/6
      - name: Run unit tests
        run: |
          bundle exec rails test
          bundle exec rspec
          sed -i 's/\/home\/runner\/work\/sroc-tcm-admin\/sroc-tcm-admin\//\/github\/workspace\//g' coverage/.resultset.json

      - name: Analyze with SonarCloud
        if: github.actor != 'dependabot[bot]'
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is provided automatically by GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # This needs to be set in your repo; settings -> secrets
